from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setMaximumSize(QtCore.QSize(16777215, 150))
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.bt_Export = QtWidgets.QPushButton(self.groupBox)
        self.bt_Export.setMinimumSize(QtCore.QSize(0, 35))
        self.bt_Export.setObjectName("bt_Export")
        self.gridLayout_2.addWidget(self.bt_Export, 1, 3, 1, 1)
        self.bt_Import = QtWidgets.QPushButton(self.groupBox)
        self.bt_Import.setMinimumSize(QtCore.QSize(0, 35))
        self.bt_Import.setObjectName("bt_Import")
        self.gridLayout_2.addWidget(self.bt_Import, 1, 2, 1, 1)
        self.bt_Start = QtWidgets.QPushButton(self.groupBox)
        self.bt_Start.setMinimumSize(QtCore.QSize(0, 35))
        self.bt_Start.setObjectName("bt_Start")
        self.gridLayout_2.addWidget(self.bt_Start, 1, 0, 1, 1)
        self.bt_Clear = QtWidgets.QPushButton(self.groupBox)
        self.bt_Clear.setMinimumSize(QtCore.QSize(0, 35))
        self.bt_Clear.setObjectName("bt_Clear")
        self.gridLayout_2.addWidget(self.bt_Clear, 1, 1, 1, 1)
        self.inputURL = QtWidgets.QPlainTextEdit(self.groupBox)
        self.inputURL.setMinimumSize(QtCore.QSize(0, 70))
        self.inputURL.setMaximumSize(QtCore.QSize(16777215, 70))
        self.inputURL.setObjectName("inputURL")
        self.gridLayout_2.addWidget(self.inputURL, 0, 0, 1, 4)
        self.gridLayout.addWidget(self.groupBox, 0, 0, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.resultView = QtWidgets.QTextBrowser(self.groupBox_2)
        self.resultView.setObjectName("resultView")
        self.gridLayout_3.addWidget(self.resultView, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox_2, 1, 0, 1, 1)
        self.progress_main = QtWidgets.QProgressBar(self.centralwidget)
        self.progress_main.setMinimumSize(QtCore.QSize(0, 5))
        self.progress_main.setMaximumSize(QtCore.QSize(16777215, 5))
        self.progress_main.setProperty("value", 24)
        self.progress_main.setTextVisible(False)
        self.progress_main.setObjectName("progress_main")
        self.gridLayout.addWidget(self.progress_main, 2, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "Control"))
        self.bt_Export.setText(_translate("MainWindow", "Export"))
        self.bt_Import.setText(_translate("MainWindow", "Import"))
        self.bt_Start.setText(_translate("MainWindow", "Start"))
        self.bt_Clear.setText(_translate("MainWindow", "Clear"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Result"))
